name: CMake on a single platform

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  BUILD_SHARED_LIBS: OFF
  MAKE_INSTALLABLE: ON
  BUILD_EXECUTABLE: ON
  BUILD_TESTING: ON

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.2.x'

      - name: Build pretty_diagnostics
        run: |
          git clone https://github.com/Excse/pretty_diagnostics
          cd pretty_diagnostics
          cmake -S . -B "${{ github.workspace }}/pretty_diagnostics/build" \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTING=OFF \
            -DMAKE_INSTALLABLE=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_INSTALL_PREFIX:PATH="${{github.workspace}}/pretty_diagnostics/install"
          cmake --build "${{ github.workspace }}/pretty_diagnostics/build" --config Release
          cmake --install "${{ github.workspace }}/pretty_diagnostics/build" --config Release

      - name: Configure Arkoi Language CMake
        run: |
          cmake -S . -B "${{ github.workspace }}/arkoi_language/build" \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DBUILD_TESTING=${{env.BUILD_TESTING}} \
            -DBUILD_EXECUTABLE=${{env.BUILD_EXECUTABLE}} \
            -DMAKE_INSTALLABLE=${{env.MAKE_INSTALLABLE}} \
            -DBUILD_SHARED_LIBS=${{env.BUILD_SHARED_LIBS}} \
            -DCMAKE_INSTALL_PREFIX:PATH="${{ github.workspace }}/arkoi_language/install" \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/pretty_diagnostics/install"

      - name: Build
        working-directory: ${{ github.workspace }}/arkoi_language/build
        run: cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{ github.workspace }}/arkoi_language/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

      - name: Test Install
        working-directory: ${{ github.workspace }}/arkoi_language/build
        run: cmake --install . --config ${{env.BUILD_TYPE}}
